// Generated by CoffeeScript 1.6.2
(function() {
  var toString, typeTest, _ref;

  toString = Object.prototype.toString;

  typeTest = function(type) {
    return function(obj) {
      return (toString.call(obj)) === ("[object " + type + "]");
    };
  };

  module.exports = {
    isArray: (_ref = Array.isArray) != null ? _ref : typeTest('Array'),
    isObject: function(obj) {
      return obj === (Object(obj));
    },
    isString: typeTest('String'),
    isNumber: typeTest('Number')
  };

}).call(this);
